# ---------
# JEKYLL CONFIGURATION
# ---------
title: Juan Pablo Perez Mejia
description: >-
  Portfolio of Juan Pablo Perez Mejia: Programmer, Innovator, and Problem Solver
# IMPORTANT: Uncomment and update URL when deploying to GitHub Pages
# url: https://juanpaperez9.github.io
# baseurl: /

# Defaults
defaults:
  -
    values:
      layout: libdoc/page

kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  style: compressed

# ---------
# LIBDOC CONFIGURATION
# ---------
playground:
  stylesheets:
    # Add custom CSS files if needed
  scripts_head:
    # Add custom JavaScript files if needed
  min_height: 300px
  metadata:
    lang: en
    cache: false
    favicon: /assets/libdoc/img/favicon/playground-android-chrome-512x512.png
    author: Juan Pablo Perez Mejia
    color: '#556e1e'

metadata:
  lang: en
  cache: false
  favicon: /assets/libdoc/img/favicon/favicon-32x32.png
  author: Juan Pablo Perez Mejia
  color: '#123456'
  image: /assets/libdoc/img/libdoc.png

# Sidebar
sidebar:
  disable_search: false
  logo:
    url: /assets/libdoc/img/profile.jpeg # Replace with your profile picture
    max_height: 40px
  additional_links:
    # Social Media Links
    - url: https://github.com/juanpaperez9
      title: <span class="i-github u-mr-xxs"></span> GitHub
      order: 0
      category: "Social Media"
    - url: https://www.linkedin.com/in/juan-pablo-perez-mejia-625372299/
      title: LinkedIn
      order: 1
      category: "Social Media"
    - url: https://app.joinhandshake.com/profiles/43519722
      title: Handshake
      order: 2
      category: "Social Media"
    - url: mailto:jpperezmejia@knox.edu
      title: Email Me
      order: 3
      category: "Social Media"

    # Juanpa in the US Links
    - url: /experience/
      title: Experience
      order: 4
      category: "Juanpa in the US"
    - url: /skills/
      title: Skills
      order: 5
      category: "Juanpa in the US"
    - url: /classes/
      title: Classes
      order: 6
      category: "Juanpa in the US"

  # Sidebar Sections
  sections:
    - title: "Social Media"
      category: true # Makes it a category, not a clickable page
      order: 0
    - title: "Experience"
      url: /_pages/experience/
      order: 1
      category: "Juanpa in the US"
      separator: true
    - title: "Skills"
      url: /_pages/skills/
      order: 2
      category: "Juanpa in the US"
      separator: true
    - title: "Classes"
      url: /_pages/classes/
      order: 3
      category: "Juanpa in the US"
      separator: true

# Badges
shields:
  # Uncomment and add custom badges if desired
  # - image_html: <img alt="GitHub Repo stars" src="https://img.shields.io/github/stars/juanpaperez9?logo=github&style=flat-square">
  #   link_url: https://github.com/juanpaperez9

# Assets
assets:
  path_from_root: /
  extensions_enabled:
    - pdf
    - js
    - css
    - jpg
    - png
    - svg
    - jpeg
  image_extensions:
    - jpg
    - png
    - svg
    - jpeg

# Syntax Highlighter
prism:
  theme: tomorrow
  font_size: 0.9em
  line_height: 1.4em
  languages:
    - markdown
    - scss
    - yaml

# ---------
# CUSTOM SECTIONS
# ---------

# General Metadata
author: Juan Pablo Perez Mejia
email: jpperezmejia@knox.edu
phone: "(312) 912-5226"
resume_url: /assets/Resume.pdf # Replace with the path to your uploaded resume
projects_url: /projects/
about_url: /about/
music_url: /music/ # Create a page for music and link it here

# Notes for Missing Sections
# Add hobbies, music interests, and any other personal information to the respective pages in `_pages/`.
# For example:
# - Create `_pages/about.md` for the "About Me" section.
# - Create `_pages/music.md` for the "Music" section.